"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import datetime
from pathlib import Path
import os
import socket
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path
import os, json
from dotenv import dotenv_values
from cryptography.hazmat.primitives import serialization
import dj_database_url


def _smart_cast(value: str):
    s = value.strip()

    # boolean
    if s.lower() in ("true", "1", "yes", "on"):
        return True
    if s.lower() in ("false", "0", "no", "off"):
        return False

    # int
    try:
        return int(s)
    except ValueError:
        pass

    # float
    try:
        return float(s)
    except ValueError:
        pass

    # lista simples por vírgula (se não for JSON explícito)
    if "," in s and not (s.startswith("{") or s.startswith("[")):
        return [item.strip() for item in s.split(",")]

    # JSON (dict/list/null/true/false/num/str)
    try:
        return json.loads(s)
    except Exception:
        return s  # string pura


START_TIME = datetime.datetime.now()
APP_STARTED = str(int(datetime.datetime.now().timestamp()))
# Versao do deploy: APP_VERSION do ambiente, senao o arquivo VERSION da raiz
# do repositorio (ver bump-version.sh). Uma string fixa no codigo envelhece no
# primeiro commit e passa a mentir sobre o que esta rodando.
def _version():
    from pathlib import Path
    env = (os.environ.get('APP_VERSION') or '').strip()
    if env:
        return env
    for base in (Path(__file__).resolve().parent.parent,
                 Path(__file__).resolve().parent.parent.parent):
        arquivo = base / 'VERSION'
        try:
            texto = arquivo.read_text().strip()
            if texto:
                return texto
        except OSError:
            continue
    return '0.0.0'


VERSION = _version()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = "/app/data"

# .env UNICO do repositorio: a raiz manda (mesmo arquivo dos docker-compose).
# Dentro do container o backend e montado em /app e o compose injeta tudo via
# env_file, entao o arquivo pode nao existir — dai o fallback para backend/.env.
ENV_FILE = next(
    (p for p in (BASE_DIR.parent / ".env", BASE_DIR / ".env") if p.is_file()),
    BASE_DIR.parent / ".env",
)

# Segredos GERADOS no primeiro boot (SECRET_KEY, RSA_*) — nao sao configuracao,
# ficam no volume de dados. Ver photoeditor/startup.py:create_default_dot_env().
SECRETS_ENV_FILE = Path(DATA_DIR) / ".env"

# Precedencia: os.environ (SO/compose) > .env da raiz > segredos gerados.
_file_env = {}
for _source in (SECRETS_ENV_FILE, ENV_FILE):  # o ultimo sobrescreve o anterior
    _file_env.update({
        k: v for k, v in (dotenv_values(_source) or {}).items()
        if k and v is not None
    })

for _key, _val in _file_env.items():
    os.environ.setdefault(_key, _val)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pk+@s=gxiu_v_z!a@8(b0d6l!j28amk_@)jg54f8le^ma99pfy'

# SECURITY WARNING: don't run with debug turned on in production!
# O padrao do sistema e DEBUG=False — ligar exige acao explicita no ambiente.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['*']


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# EN e o padrao do sistema e o fallback de toda traducao (ver photoeditor/i18n.py).
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = 'en'
TIME_ZONE = 'America/Sao_Paulo'

DEFAULT_LANGUAGE = 'en'
SUPPORTED_LANGUAGES = ['en', 'pt-br']

RSA_PUB_KEY = ""

# 1) Valores do(s) arquivo(s) .env ja carregados acima
_env = _file_env


def _is_raw_string_setting(key: str) -> bool:
    """Segredos e chaves NUNCA passam pelo _smart_cast.

    O _smart_cast transforma qualquer string com virgula em lista (e digitos em
    int, etc.). Uma SECRET_KEY sorteada contendo virgula virava ``list``, e a
    derivacao de chaves quebrava com "'list' object has no attribute
    'encode'". Segredo e sempre texto opaco.
    """
    return key.endswith((
        "SECRET", "SECRET_KEY", "PASSWORD", "PASSPHRASE", "TOKEN", "KEY", "KEY_PATH",
    ))


# 2) Promove as variáveis MAIÚSCULAS a settings do módulo.
#    O valor efetivo vem de os.environ (SO/compose manda mais que o arquivo);
#    o .env só entra como default — ver o setdefault feito junto ao BASE_DIR.
for key, val in (_env or {}).items():
    if not key or not key.isupper():
        continue
    if key == "RSA_PASSPHRASE":
        continue
    raw = os.environ.get(key, val)
    globals()[key] = raw if _is_raw_string_setting(key) else _smart_cast(raw)

# Load Public key
try:
    PUBLIC_KEY = serialization.load_pem_public_key(
        f"-----BEGIN PUBLIC KEY-----\n{RSA_PUB_KEY}\n-----END PUBLIC KEY-----".encode("UTF-8")
        )
except Exception as e:
    print("Error loading RSA public KEY")
    if os.path.isfile(ENV_FILE):
        raise e

# Automatically add the current machine's local IP address to ALLOWED_HOSTS
try:
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    if local_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(local_ip)
except Exception:
    pass

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'rest_framework',
    'corsheaders',
    'django_filters',

    'photoeditor'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Django admin publico: entra como o usuario ``admin`` padrao (sem senha).
    'photoeditor.middleware.PublicAdminMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SEMPRE PostgreSQL — nao existe fallback para sqlite, nem em DEBUG.
# Sem esse guard, um comando rodado sem POSTGRES_URL (tipicamente o
# `createsuperuser` do primeiro setup) criaria silenciosamente um sqlite local
# e gravaria o super admin no banco errado.
POSTGRES_URL = os.environ.get('POSTGRES_URL', '').strip()
if not POSTGRES_URL:
    raise ImproperlyConfigured(
        'POSTGRES_URL is not set. This project always uses PostgreSQL — there is '
        'no sqlite fallback. Set POSTGRES_URL in the root .env (e.g. '
        'postgresql://user:pass@host:5432/dbname) before running manage.py.'
    )

DATABASES = {
    'default': dj_database_url.parse(POSTGRES_URL, conn_max_age=600)
}

if not DATABASES['default'].get('ENGINE', '').endswith('postgresql'):
    raise ImproperlyConfigured(
        f"POSTGRES_URL must point to a PostgreSQL database "
        f"(got ENGINE={DATABASES['default'].get('ENGINE')!r})."
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

USE_THOUSAND_SEPARATOR = True

SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_SECONDS = 60 * 60  # 60 minutos
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Prefixo proprio: /static/ e do build do React servido pelo nginx; os
# estaticos do Django admin saem por /django-static/ (proxy para o backend).
STATIC_URL = '/django-static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # usado em produção

if DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'photoeditor', 'static')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher'
]

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # <-- troca 'error' por 'danger'
}

# Reverse proxy / TLS
# The app always runs behind nginx (and possibly an upstream TLS-terminating
# proxy). Trust X-Forwarded-Proto so request.is_secure()/request.scheme and
# every absolute link (build_absolute_uri, redirects) reflect
# the external scheme — https even when this hop arrives as plain HTTP on port 80.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# FORCE_TLS mirrors the nginx flag: when on, cookies are marked Secure and Django
# also redirects plain HTTP to HTTPS (belt-and-suspenders with nginx). Default on.
FORCE_TLS = os.environ.get('FORCE_TLS', 'True').lower() in ('true', '1', 'yes', 'on')

SESSION_COOKIE_SECURE = FORCE_TLS
CSRF_COOKIE_SECURE = FORCE_TLS

# CSRF trusted origins (scheme://host) — needed once cookies are Secure and the
# app is served over https through the proxy.
_csrf_trusted = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(',') if o.strip()]

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # nginx already redirects/HSTS; only let Django do it too when TLS is forced,
    # otherwise a FORCE_TLS=false deployment would break its own HTTP access.
    SECURE_SSL_REDIRECT = FORCE_TLS
    if FORCE_TLS:
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

CRONJOBS = [
    #('* * * * *', 'photoeditor.cron.mailer'),
]

# Django REST Framework
# Sistema publico e nao autenticado: nenhuma classe de autenticacao e tudo
# liberado por padrao. Sem SessionAuthentication o DRF tambem nao exige CSRF
# das chamadas da SPA.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'UNAUTHENTICATED_USER': None,
}

# CORS
CORS_ALLOW_CREDENTIALS = True
_cors_origins = os.environ.get('CORS_ORIGINS', 'http://localhost:3000')
if _cors_origins.strip() == '*':
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

# Branding — nome/dominio do produto, configuraveis por ambiente
BRAND_NAME = os.environ.get('BRAND_NAME', 'PhotoEditor')
BRAND_DOMAIN = os.environ.get('BRAND_DOMAIN', 'photoeditor.com.br')
BRAND_CONTACT_EMAIL = os.environ.get('BRAND_CONTACT_EMAIL', f'contato@{BRAND_DOMAIN}')

# Email / SMTP
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'{BRAND_NAME} <noreply@{BRAND_DOMAIN}>')

# ---------------------------------------------------------------------------
# Logging — SEMPRE para o stdout/stderr do processo (docker logs)
# ---------------------------------------------------------------------------
# Sem esta configuracao o Django cai no DEFAULT_LOGGING, cujo handler de console
# tem o filtro ``require_debug_true``: com DEBUG=False (o padrao do projeto)
# nada e emitido, e os loggers da aplicacao ("photoeditor.*") ficam
# sem handler nenhum. Aqui o console e incondicional: em container, log que nao
# vai para o stdout simplesmente nao existe.
LOG_LEVEL = (os.environ.get('LOG_LEVEL', 'INFO') or 'INFO').strip().upper()
DJANGO_LOG_LEVEL = (os.environ.get('DJANGO_LOG_LEVEL', LOG_LEVEL) or LOG_LEVEL).strip().upper()
# Requisicoes HTTP do runserver/uwsgi sao ruidosas; ligue com SQL_LOG_LEVEL=DEBUG.
SQL_LOG_LEVEL = (os.environ.get('SQL_LOG_LEVEL', 'WARNING') or 'WARNING').strip().upper()

LOGGING = {
    'version': 1,
    # Nao desabilita loggers ja criados no import das settings/apps.
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        # stdout (nao stderr): o docker captura os dois, mas o stdout mantem a
        # ordem em relacao aos echos do entrypoint e ao banner do bootstrap.
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'standard',
            'level': 'DEBUG',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': SQL_LOG_LEVEL,
            'propagate': False,
        },
        # Tracebacks de 500 no stdout — sem isto o Django so tentaria o
        # AdminEmailHandler, que em container nao chega a lugar nenhum.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Loggers da aplicacao: "photoeditor.*" (getLogger(__name__)).
        'photoeditor': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
