"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

O backend roda DENTRO do app desktop: o processo filho iniciado por
``desktop/server.py`` (waitress em 127.0.0.1) recebe tudo por variavel de
ambiente — pasta do projeto, pasta de dados, build do frontend, modelo, token.
"""

import datetime
import json
import logging
import os
import sys
from pathlib import Path

from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured
from dotenv import dotenv_values

from core.secret_key import ensure_secrets_file


def _smart_cast(value: str):
    s = value.strip()

    # boolean
    if s.lower() in ("true", "1", "yes", "on"):
        return True
    if s.lower() in ("false", "0", "no", "off"):
        return False

    # int
    try:
        return int(s)
    except ValueError:
        pass

    # float
    try:
        return float(s)
    except ValueError:
        pass

    # lista simples por vírgula (se não for JSON explícito)
    if "," in s and not (s.startswith("{") or s.startswith("[")):
        return [item.strip() for item in s.split(",")]

    # JSON (dict/list/null/true/false/num/str)
    try:
        return json.loads(s)
    except Exception:
        return s  # string pura


START_TIME = datetime.datetime.now()
APP_STARTED = str(int(datetime.datetime.now().timestamp()))


# Versao do app: APP_VERSION do ambiente, senao o arquivo VERSION da raiz, que
# o tools/build.py gera a partir das Releases do GitHub (regra 17). Uma string
# fixa no codigo envelhece e passa a mentir sobre o que esta rodando.
def _version():
    env = (os.environ.get('APP_VERSION') or '').strip()
    if env:
        return env
    for base in (Path(__file__).resolve().parent.parent,
                 Path(__file__).resolve().parent.parent.parent):
        arquivo = base / 'VERSION'
        try:
            texto = arquivo.read_text().strip()
            if texto:
                return texto
        except OSError:
            continue
    return '0.0.0'


VERSION = _version()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Raiz do app: o repositorio em desenvolvimento, <instalacao>/app no pacote.
APP_ROOT = BASE_DIR.parent

# Pasta do app na HOME do usuario, igual nos tres SOs: ``~/.photoe`` (banco do
# app, segredos gerados, perfil do navegador, capas, logs). Nunca dentro da
# instalacao, que pode ser somente leitura. O launcher repassa a mesma pasta
# (desktop/paths.py); DATA_DIR no ambiente sobrescreve.
DATA_DIR = Path(os.environ.get('DATA_DIR') or Path.home() / '.photoe')
DATA_DIR.mkdir(parents=True, exist_ok=True)

# .env da raiz: OPCIONAL, so para desenvolvimento (o app instalado nao tem um).
ENV_FILE = APP_ROOT / ".env"

# Segredos GERADOS no primeiro uso (SECRET_KEY) — nao sao configuracao, sao
# estado da maquina: ficam na pasta de dados do usuario.
SECRETS_ENV_FILE = ensure_secrets_file(DATA_DIR / ".env")

# Precedencia: os.environ > .env da raiz > segredos gerados.
_file_env = {}
for _source in (SECRETS_ENV_FILE, ENV_FILE):  # o ultimo sobrescreve o anterior
    if not _source.is_file():
        continue
    _file_env.update({
        k: v for k, v in (dotenv_values(_source) or {}).items()
        if k and v is not None
    })

for _key, _val in _file_env.items():
    os.environ.setdefault(_key, _val)

# Sobrescrito pelo SECRET_KEY de SECRETS_ENV_FILE (promovido logo abaixo).
SECRET_KEY = 'django-insecure-pk+@s=gxiu_v_z!a@8(b0d6l!j28amk_@)jg54f8le^ma99pfy'

# SECURITY WARNING: don't run with debug turned on in production!
# O padrao do sistema e DEBUG=False — ligar exige acao explicita no ambiente.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# O servidor so escuta em 127.0.0.1. Host fixo tambem barra DNS rebinding: um
# site externo que resolva o proprio nome para 127.0.0.1 chega com outro Host.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Token da sessao do app desktop, sorteado a cada execucao pelo launcher e
# entregue ao navegador embarcado como cookie (ver AppTokenMiddleware). Vazio
# (ex.: ``manage.py runserver`` em dev) = sem verificacao.
APP_TOKEN = os.environ.get('APP_TOKEN', '')


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# EN e o padrao do sistema e o fallback de toda traducao (ver photoeditor/i18n.py).
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = 'en'
TIME_ZONE = os.environ.get('TIME_ZONE', 'America/Sao_Paulo')

DEFAULT_LANGUAGE = 'en'
SUPPORTED_LANGUAGES = ['en', 'pt-br']

# 1) Valores do(s) arquivo(s) .env ja carregados acima
_env = _file_env


def _is_raw_string_setting(key: str) -> bool:
    """Segredos e chaves NUNCA passam pelo _smart_cast.

    O _smart_cast transforma qualquer string com virgula em lista (e digitos em
    int, etc.). Uma SECRET_KEY sorteada contendo virgula virava ``list``, e a
    derivacao de chaves quebrava com "'list' object has no attribute
    'encode'". Segredo e sempre texto opaco.
    """
    return key.endswith((
        "SECRET", "SECRET_KEY", "PASSWORD", "PASSPHRASE", "TOKEN", "KEY", "KEY_PATH",
    ))


# 2) Promove as variáveis MAIÚSCULAS a settings do módulo.
#    O valor efetivo vem de os.environ (SO/launcher manda mais que o arquivo);
#    o .env só entra como default — ver o setdefault acima.
for key, val in (_env or {}).items():
    if not key or not key.isupper():
        continue
    raw = os.environ.get(key, val)
    globals()[key] = raw if _is_raw_string_setting(key) else _smart_cast(raw)

# Settings que o Django exige como LISTA: um valor so, sem virgula, o
# _smart_cast deixa como string — e o Django itera letra por letra.
for _key in ('CSRF_TRUSTED_ORIGINS',):
    if isinstance(globals().get(_key), str):
        globals()[_key] = [v.strip() for v in globals()[_key].split(',') if v.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'photoeditor'
]

MIDDLEWARE = [
    # Primeiro de todos: requisicao sem o token da sessao do app nao chega a
    # nenhuma view (nem aos estaticos).
    'photoeditor.middleware.AppTokenMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Estaticos do Django admin e o build do React (WHITENOISE_ROOT).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Django admin publico: entra como o usuario ``admin`` padrao (sem senha).
    'photoeditor.middleware.PublicAdminMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Pasta do projeto de fotos (o evento), escolhida no app desktop e repassada
# pelo launcher. Tudo o que o editor le e grava vive nela — inclusive o banco,
# para que o catalogo e os ajustes acompanhem as fotos de cada evento.
_project_root = (os.environ.get('PROJECT_ROOT') or '').strip()
PROJECT_ROOT = Path(_project_root).expanduser() if _project_root else None

# Sem PROJECT_ROOT o servidor sobe no MODO HOME: so a tela inicial (projetos
# recentes) e suas APIs — ver photoeditor/urls.py. Nao ha catalogo, entao o
# banco e um SQLite em memoria que nada grava de verdade.
HOME_MODE = PROJECT_ROOT is None

# Com projeto, o banco e SEMPRE o SQLite dele. Pasta informada que nao existe
# falha na hora, com mensagem clara, em vez de criar um banco em outro lugar e
# "perder" o catalogo na proxima execucao.
if not HOME_MODE and not PROJECT_ROOT.is_dir():
    raise ImproperlyConfigured(
        f'PROJECT_ROOT ({PROJECT_ROOT}) is not a folder. Open the photo project '
        f'from the desktop app, or set PROJECT_ROOT to the event folder.'
    )

if HOME_MODE:
    RAW_DIR = PROJECT_DATA_DIR = DELETED_DIR = PUBLISH_DIR = MASKS_DIR = None
else:
    PROJECT_ROOT = PROJECT_ROOT.resolve()
    RAW_DIR = PROJECT_ROOT / 'raw'                    # originais (somente JPEG)
    PROJECT_DATA_DIR = PROJECT_ROOT / 'project_data'  # SQLite + caches gerados
    DELETED_DIR = PROJECT_ROOT / 'deleted'            # fotos excluidas (movidas)
    PUBLISH_DIR = PROJECT_ROOT / 'publicar'           # saida do Exportar
    # Mascaras das camadas (PNG por hash do conteudo). Nao e cache: a edicao
    # gravada aponta para elas, entao moram fora de project_data/cache.
    MASKS_DIR = PROJECT_DATA_DIR / 'masks'
    # O SQLite cria o arquivo, mas nao a pasta — ela tem de existir antes do migrate.
    PROJECT_DATA_DIR.mkdir(exist_ok=True)

# Banco do APP (nao do evento): a lista de projetos da tela Home. Quem registra
# e o app desktop, ao abrir um projeto; a Home le e remove. Acesso por sqlite3
# puro, fora do ORM — ver photoeditor/services/recent_projects.py.
APP_DB = Path(os.environ.get('APP_DB') or DATA_DIR / 'photoe.db')
# Capas dos cards da Home (uma miniatura por projeto), geradas sob demanda.
PROJECT_COVERS_DIR = DATA_DIR / 'covers'

# Modelo de segmentacao (SAM 2.1 tiny em ONNX) que transforma o traco do
# pincel em mascara do objeto. Vai no pacote do app (``tools/build.py model``).
SEGMENT_MODEL_DIR = Path(
    os.environ.get('SEGMENT_MODEL_DIR') or APP_ROOT / 'models' / 'sam2.1-hiera-tiny')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:' if HOME_MODE else PROJECT_DATA_DIR / 'db.sqlite3',
        # Espera o lock em vez de falhar com "database is locked" quando duas
        # requisicoes gravam ao mesmo tempo.
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

USE_THOUSAND_SEPARATOR = True

SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Prefixo proprio: /static/ e do build do React; os estaticos do Django admin
# saem por /django-static/. O WhiteNoise le direto das apps (USE_FINDERS), sem
# collectstatic — o pacote do app nao precisa gerar nada no boot.
STATIC_URL = '/django-static/'
WHITENOISE_USE_FINDERS = True

# Build do React (index.html, /static/js, /assets...), servido na raiz pelo
# WhiteNoise; o que nao for arquivo cai na SPA (core/urls.py).
FRONTEND_BUILD_DIR = Path(
    os.environ.get('FRONTEND_BUILD_DIR') or APP_ROOT / 'frontend' / 'build')
WHITENOISE_ROOT = FRONTEND_BUILD_DIR if FRONTEND_BUILD_DIR.is_dir() else None

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher'
]

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # <-- troca 'error' por 'danger'
}

# Seguranca: o servidor e local (http://127.0.0.1), sem TLS nem proxy na frente.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Django REST Framework
# Sistema publico e nao autenticado: nenhuma classe de autenticacao e tudo
# liberado por padrao. Sem SessionAuthentication o DRF tambem nao exige CSRF
# das chamadas da SPA. Quem barra o resto da maquina e o AppTokenMiddleware.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'UNAUTHENTICATED_USER': None,
}

# Branding — nome/dominio do produto, configuraveis por ambiente
BRAND_NAME = os.environ.get('BRAND_NAME', 'PhotoEditor')
BRAND_DOMAIN = os.environ.get('BRAND_DOMAIN', 'photoeditor.com.br')
BRAND_CONTACT_EMAIL = os.environ.get('BRAND_CONTACT_EMAIL', f'contato@{BRAND_DOMAIN}')
# Pagina do software: vai no EXIF (Software) das fotos exportadas.
BRAND_URL = os.environ.get('BRAND_URL', 'https://github.com/helviojunior/photo-editor')

# Email / SMTP
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'{BRAND_NAME} <noreply@{BRAND_DOMAIN}>')

# ---------------------------------------------------------------------------
# Logging — arquivo de log do usuario + stdout quando houver um
# ---------------------------------------------------------------------------
# O launcher passa LOG_FILE (pasta de logs do SO, ver desktop/paths.py): o app
# instalado nao tem terminal, e log que nao vai para arquivo nao existe. Em
# desenvolvimento o mesmo log sai tambem no terminal.
#
# Sem esta configuracao o Django cai no DEFAULT_LOGGING, cujo handler de console
# tem o filtro ``require_debug_true``: com DEBUG=False (o padrao do projeto)
# nada seria emitido.
LOG_LEVEL = (os.environ.get('LOG_LEVEL', 'INFO') or 'INFO').strip().upper()
DJANGO_LOG_LEVEL = (os.environ.get('DJANGO_LOG_LEVEL', LOG_LEVEL) or LOG_LEVEL).strip().upper()
SQL_LOG_LEVEL = (os.environ.get('SQL_LOG_LEVEL', 'WARNING') or 'WARNING').strip().upper()
LOG_FILE = (os.environ.get('LOG_FILE') or '').strip()

_log_handlers = {}
if sys.stdout is not None:
    _log_handlers['console'] = {
        'class': 'logging.StreamHandler',
        'stream': 'ext://sys.stdout',
        'formatter': 'standard',
        'level': 'DEBUG',
    }
if LOG_FILE:
    Path(LOG_FILE).parent.mkdir(parents=True, exist_ok=True)
    _log_handlers['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': LOG_FILE,
        'maxBytes': 5 * 1024 * 1024,
        'backupCount': 3,
        'encoding': 'utf-8',
        'formatter': 'standard',
        'level': 'DEBUG',
    }
if not _log_handlers:
    _log_handlers['null'] = {'class': 'logging.NullHandler'}
_LOG_TO = list(_log_handlers)

LOGGING = {
    'version': 1,
    # Nao desabilita loggers ja criados no import das settings/apps.
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': _log_handlers,
    'root': {
        'handlers': _LOG_TO,
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': _LOG_TO,
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': _LOG_TO,
            'level': SQL_LOG_LEVEL,
            'propagate': False,
        },
        # Tracebacks de 500 no log — sem isto o Django so tentaria o
        # AdminEmailHandler, que num app desktop nao chega a lugar nenhum.
        'django.request': {
            'handlers': _LOG_TO,
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': _LOG_TO,
            'level': 'WARNING',
            'propagate': False,
        },
        # Loggers da aplicacao: "photoeditor.*" (getLogger(__name__)).
        'photoeditor': {
            'handlers': _LOG_TO,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'waitress': {
            'handlers': _LOG_TO,
            'level': 'WARNING',
            'propagate': False,
        },
        # "Task queue depth is N": so as threads ocupadas gerando miniaturas
        # da filmstrip — normal, e encheria o log a cada projeto aberto.
        'waitress.queue': {
            'handlers': _LOG_TO,
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
