# Generated by Django 5.2.3 on 2026-09-23 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('deleted_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('missing', 'Missing')], db_index=True, default='active', max_length=16)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mtime_ns', models.BigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('orientation', models.PositiveSmallIntegerField(default=1)),
                ('captured_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('captured_at'), nulls_last=True), 'file_name'],
            },
        ),
    ]
