# Generated by Django 5.2.3 on 2026-09-23 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('delete', 'Delete'), ('adjust', 'Adjust'), ('auto', 'Auto'), ('preset', 'Preset'), ('reset', 'Reset')], max_length=16)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('undone_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='photoeditor.photo')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
