# Generated by Django 5.2.3 on 2026-09-23 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('exposure', models.FloatField(default=0)),
                ('contrast', models.FloatField(default=0)),
                ('highlights', models.FloatField(default=0)),
                ('shadows', models.FloatField(default=0)),
                ('whites', models.FloatField(default=0)),
                ('blacks', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('tint', models.FloatField(default=0)),
                ('vibrance', models.FloatField(default=0)),
                ('saturation', models.FloatField(default=0)),
                ('preset', models.CharField(blank=True, default='', max_length=32)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='photoeditor.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
