# Generated by Django 5.2.3 on 2026-09-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0003_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exported_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
