# Generated by Django 5.2.3 on 2026-09-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0004_photo_exported_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='crop_angle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='crop_cx',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='crop_cy',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='crop_scale',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='kind',
            field=models.CharField(choices=[('delete', 'Delete'), ('adjust', 'Adjust'), ('auto', 'Auto'), ('preset', 'Preset'), ('reset', 'Reset'), ('crop', 'Crop')], max_length=16),
        ),
    ]
