# Generated by Django 5.2.3 on 2026-09-27 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0006_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('layers', models.JSONField(blank=True, default=list)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges', to='photoeditor.photo')),
                ('output', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_source', to='photoeditor.photo')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
