# Generated by Django 5.2.3 on 2026-09-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0007_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merge',
            name='output',
        ),
    ]
