# Generated by Django 5.2.3 on 2026-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0008_remove_merge_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='merge',
            name='base_mask',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='merge',
            name='base_opacity',
            field=models.FloatField(default=1.0),
        ),
    ]
