# Generated by Django 5.2.3 on 2026-09-27 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0009_merge_base_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='copy_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='photoeditor.photo'),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='kind',
            field=models.CharField(choices=[('delete', 'Delete'), ('adjust', 'Adjust'), ('auto', 'Auto'), ('preset', 'Preset'), ('reset', 'Reset'), ('crop', 'Crop'), ('layer', 'Layer'), ('duplicate', 'Duplicate')], max_length=16),
        ),
    ]
