# Generated by Django 5.2.3 on 2026-09-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0010_photo_copy_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='kind',
            field=models.CharField(choices=[('delete', 'Delete'), ('adjust', 'Adjust'), ('auto', 'Auto'), ('preset', 'Preset'), ('reset', 'Reset'), ('crop', 'Crop'), ('layer', 'Layer'), ('duplicate', 'Duplicate'), ('cover', 'Cover')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('is_cover',), name='photo_single_cover'),
        ),
    ]
