# Generated by Django 5.2.3 on 2026-10-01 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0011_photo_is_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=64)),
                ('media_id', models.CharField(blank=True, default='', max_length=64)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('caption', models.TextField(blank=True, default='')),
                ('photos', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='adjustment',
            name='crop_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='instagram_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_versions', to='photoeditor.photo'),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='kind',
            field=models.CharField(choices=[('delete', 'Delete'), ('adjust', 'Adjust'), ('auto', 'Auto'), ('preset', 'Preset'), ('reset', 'Reset'), ('crop', 'Crop'), ('layer', 'Layer'), ('duplicate', 'Duplicate'), ('cover', 'Cover'), ('instagram', 'Instagram')], max_length=16),
        ),
    ]
